title: Max Rydahl Andersen
author: Max Rydahl Andersen

profiles:
  development:
    disqus_developer: true
    dev: true
  production:
    base_url: http://xam.dk/test
    deploy:
      type: rsync
      host: ftp.xam.dk
      path: /test
      user: xam.dk

google_analytics: UA-70032-1
flattr_username: maxandersen
disqus: maxandersen

twitter_url: http://maxandersen.org/@
googleplus_url: http://maxandersen.org/+
linkedin_url: http://linkedin.com/maxandersen
profblog_url: http://blog.xam.dk
mail_url: mailto:blog@xam.dk

biotags: Danish, Open Source, JBoss Tools, Hibernate, JBoss, Eclipse
